const express = require('express');
const config = require('./config');
const router = require('./router');
const db = require('./models/db');

var app = express();

// Swagger doc
const expressSwagger = require('express-swagger-generator')(app);
const options = {
    swaggerDefinition: {
        // Like the one described here: https://swagger.io/specification/#infoObject
        info: {
            title: 'Todo list API',
            version: '1.0.0',
            description: 'Express API with autogenerated swagger doc',
        },
        host: config.url+":"+config.port,
        basePath: '/api',
        produces: [
            "application/json"
        ],
        schemes: ['http']
    },
    basedir: __dirname,
    files: ['./controller/**/*.js', './schema/**/*.js'] // Where to look to find specification to auto generate swagger json file
};
expressSwagger(options)


// Routers
app.use('/api', router);

/* Launch server */
app.listen(config.port, () => {
    console.log("Server listenning on", config.url+":"+config.port);
});

/* Connect to database */
db.on('connect', () => {
    console.log('Connected to Redis on', config.redis_host+":"+config.redis_port);
});